# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BagMMC-BjPUZrF-u1KXlFHVRfJVIVV5C
"""

!pip install streamlit pandas -q

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
-O cloudflared

!chmod +x cloudflared

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fashion_app.py
# import streamlit as st
# import pandas as pd
# from datetime import date
# 
# st.set_page_config(
#     page_title="오늘 뭐 입지?",
#     page_icon="👕",
#     layout="wide"
# )
# 
# st.title("👕 오늘 뭐 입지?")
# st.write("날씨, 기온, 성별, 스타일에 따라 오늘의 코디를 추천해주는 앱")
# 
# # Sidebar
# st.sidebar.header("오늘의 정보 입력")
# 
# gender = st.sidebar.selectbox(
#     "성별 선택",
#     ["남성", "여성"]
# )
# 
# today = st.sidebar.date_input(
#     "날짜 선택",
#     date.today()
# )
# 
# weather = st.sidebar.selectbox(
#     "날씨 선택",
#     ["맑음", "흐림", "비", "눈", "바람 많음"]
# )
# 
# temperature = st.sidebar.slider(
#     "기온 선택 (℃)",
#     -10, 35, 15
# )
# 
# style = st.sidebar.selectbox(
#     "스타일 선택",
#     ["캐주얼", "포멀", "스트릿"]
# )
# 
# 
# def recommend_outfit(gender, weather, temperature, style):
#     outfits = {
#         "남성": {
#             "캐주얼": {
#                 "hot": ["반팔 티셔츠", "반바지", "없음", "스니커즈"],
#                 "mid": ["맨투맨", "데님 팬츠", "바람막이", "운동화"],
#                 "cold": ["니트", "기모 팬츠", "코트", "부츠"]
#             },
#             "포멀": {
#                 "hot": ["반팔 셔츠", "슬랙스", "없음", "로퍼"],
#                 "mid": ["셔츠", "슬랙스", "블레이저", "로퍼"],
#                 "cold": ["목폴라", "슬랙스", "롱코트", "첼시부츠"]
#             },
#             "스트릿": {
#                 "hot": ["오버핏 반팔", "와이드 팬츠", "없음", "하이탑"],
#                 "mid": ["후드티", "카고 팬츠", "자켓", "스니커즈"],
#                 "cold": ["기모 후드티", "와이드 팬츠", "패딩", "워커"]
#             }
#         },
#         "여성": {
#             "캐주얼": {
#                 "hot": ["반팔 티셔츠", "데님 쇼츠", "없음", "스니커즈"],
#                 "mid": ["가디건", "데님 팬츠", "자켓", "운동화"],
#                 "cold": ["니트", "롱스커트", "코트", "부츠"]
#             },
#             "포멀": {
#                 "hot": ["블라우스", "슬랙스", "없음", "로퍼"],
#                 "mid": ["셔츠", "슬랙스", "블레이저", "로퍼"],
#                 "cold": ["니트", "슬랙스", "롱코트", "롱부츠"]
#             },
#             "스트릿": {
#                 "hot": ["크롭 티셔츠", "와이드 팬츠", "없음", "스니커즈"],
#                 "mid": ["후드집업", "카고 팬츠", "레더 자켓", "운동화"],
#                 "cold": ["기모 후드티", "와이드 팬츠", "숏패딩", "워커"]
#             }
#         }
#     }
# 
#     if temperature >= 23:
#         season = "hot"
#     elif temperature >= 10:
#         season = "mid"
#     else:
#         season = "cold"
# 
#     top, bottom, outer, shoes = outfits[gender][style][season]
# 
#     weather_tip = ""
# 
#     if weather == "비":
#         outer = "방수 자켓"
#         shoes = "방수 신발"
#         weather_tip = "우산 필수 ☔"
#     elif weather == "눈":
#         outer = "패딩"
#         shoes = "방한 부츠"
#         weather_tip = "따뜻하게 입으세요 ❄️"
#     elif weather == "바람 많음":
#         outer = "바람막이"
#         weather_tip = "바람막이 추천 🌬️"
#     elif weather == "흐림":
#         weather_tip = "밝은 색 포인트 추천 🌥️"
#     else:
#         weather_tip = "가볍고 산뜻한 코디 추천 ☀️"
# 
#     return top, bottom, outer, shoes, weather_tip
# 
# 
# top, bottom, outer, shoes, weather_tip = recommend_outfit(
#     gender, weather, temperature, style
# )
# 
# # Summary
# st.subheader("📌 오늘의 정보")
# 
# col1, col2, col3, col4, col5 = st.columns(5)
# 
# col1.metric("성별", gender)
# col2.metric("날짜", str(today))
# col3.metric("날씨", weather)
# col4.metric("기온", f"{temperature}℃")
# col5.metric("스타일", style)
# 
# st.markdown("---")
# 
# # Outfit table
# st.subheader("👗 추천 코디")
# 
# outfit_df = pd.DataFrame({
#     "구분": ["상의", "하의", "아우터", "신발"],
#     "추천": [top, bottom, outer, shoes]
# })
# 
# st.table(outfit_df)
# 
# # Result
# st.subheader("🧥 오늘의 한 줄 코디")
# 
# summary = f"""
# 오늘은 **{weather}**, 기온은 **{temperature}℃**입니다.
# **{gender} {style} 스타일**로
# **{top} + {bottom} + {outer} + {shoes}** 조합을 추천합니다.
# """
# 
# st.success(summary)
# 
# st.subheader("💡 스타일 팁")
# st.info(weather_tip)
# 
# # Temperature warning
# st.subheader("🔥 오늘의 옷차림 난이도")
# 
# if temperature >= 28:
#     st.warning("더운 날씨입니다. 얇고 통풍 잘 되는 옷 추천")
# elif temperature <= 5:
#     st.error("매우 추운 날씨입니다. 보온 필수")
# else:
#     st.success("무난하게 입기 좋은 날씨입니다.")

!streamlit run fashion_app.py \
--server.port 8501 \
--server.address 0.0.0.0 &

!./cloudflared tunnel --url http://localhost:8501

!cat streamlit.log