# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jtIqXgISUG9Lx-HOaAzfGoXJt226Jvz
"""

!pip install streamlit pandas -q

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
-O cloudflared

!chmod +x cloudflared

# Commented out IPython magic to ensure Python compatibility.
# %%writefile music_app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(page_title="Music Mood Recommender", page_icon="🎧", layout="wide")
# 
# st.title("🎧 Music Mood Recommender")
# st.write("기분, 상황, 장르, 에너지에 따라 오늘 들을 노래를 추천해주는 앱입니다.")
# 
# songs = [
#     ["Ditto", "NewJeans", "K-Pop", "calm", "study", 3.1, 85, 60],
#     ["Hype Boy", "NewJeans", "K-Pop", "happy", "walk", 3.0, 95, 85],
#     ["Supernova", "aespa", "K-Pop", "energetic", "workout", 2.9, 92, 95],
#     ["Love Wins All", "IU", "Ballad", "sad", "alone", 4.5, 90, 45],
#     ["밤양갱", "BIBI", "R&B", "calm", "night", 2.4, 88, 55],
#     ["Seven", "Jung Kook", "Pop", "happy", "date", 3.1, 94, 80],
#     ["Cruel Summer", "Taylor Swift", "Pop", "happy", "walk", 2.9, 96, 88],
#     ["Anti-Hero", "Taylor Swift", "Pop", "lonely", "alone", 3.3, 91, 65],
#     ["Snooze", "SZA", "R&B", "calm", "night", 3.4, 89, 50],
#     ["Kill Bill", "SZA", "R&B", "dark", "alone", 2.6, 90, 70],
#     ["Blinding Lights", "The Weeknd", "Pop", "energetic", "drive", 3.3, 98, 90],
#     ["Save Your Tears", "The Weeknd", "Pop", "lonely", "night", 3.6, 93, 68],
#     ["OMG", "NewJeans", "K-Pop", "happy", "walk", 3.5, 90, 78],
#     ["To. X", "TAEYEON", "Ballad", "sad", "alone", 2.8, 87, 50],
#     ["Dynamite", "BTS", "K-Pop", "happy", "party", 3.3, 97, 92],
#     ["Spring Day", "BTS", "Ballad", "sad", "night", 4.3, 92, 48],
#     ["Attention", "Charlie Puth", "Pop", "dark", "drive", 3.5, 88, 75],
#     ["Peaches", "Justin Bieber", "R&B", "chill", "date", 3.3, 91, 62],
#     ["As It Was", "Harry Styles", "Pop", "bittersweet", "walk", 2.8, 95, 76],
#     ["OMG", "Usher", "Dance", "energetic", "party", 4.3, 86, 94],
# ]
# 
# df = pd.DataFrame(songs, columns=[
#     "Title", "Artist", "Genre", "Mood", "Situation",
#     "Length", "Popularity", "Energy"
# ])
# 
# st.sidebar.header("🎛️ 추천 조건")
# 
# mood = st.sidebar.selectbox(
#     "오늘 기분",
#     ["happy", "sad", "calm", "energetic", "lonely", "dark", "chill", "bittersweet"]
# )
# 
# situation = st.sidebar.selectbox(
#     "듣는 상황",
#     ["study", "walk", "workout", "alone", "night", "date", "drive", "party"]
# )
# 
# genres = st.sidebar.multiselect(
#     "좋아하는 장르",
#     ["K-Pop", "Pop", "Ballad", "R&B", "Dance"],
#     default=["K-Pop", "Pop"]
# )
# 
# energy_preference = st.sidebar.slider("원하는 에너지", 0, 100, 70)
# max_length = st.sidebar.slider("최대 곡 길이(분)", 2.0, 5.0, 4.0)
# popularity_weight = st.sidebar.slider("인기도 중요도", 0.0, 2.0, 1.0)
# 
# def calculate_score(row):
#     score = 0
# 
#     if row["Mood"] == mood:
#         score += 30
#     elif mood in ["sad", "lonely", "bittersweet"] and row["Mood"] in ["sad", "lonely", "bittersweet"]:
#         score += 15
#     elif mood in ["happy", "energetic", "chill"] and row["Mood"] in ["happy", "energetic", "chill"]:
#         score += 12
# 
#     if row["Situation"] == situation:
#         score += 25
# 
#     if row["Genre"] in genres:
#         score += 20
# 
#     energy_gap = abs(row["Energy"] - energy_preference)
#     score += max(0, 20 - energy_gap * 0.3)
# 
#     if row["Length"] <= max_length:
#         score += 10
#     else:
#         score -= (row["Length"] - max_length) * 10
# 
#     score += row["Popularity"] * popularity_weight * 0.25
# 
#     return round(score, 1)
# 
# df["Recommendation Score"] = df.apply(calculate_score, axis=1)
# recommended = df.sort_values("Recommendation Score", ascending=False)
# 
# top5 = recommended.head(5)
# 
# st.subheader("🏆 오늘의 추천 노래 TOP 5")
# 
# for rank, (_, row) in enumerate(top5.iterrows(), start=1):
#     st.markdown(f"""
#     ## {rank}. {row['Title']} - {row['Artist']}
#     **장르:** {row['Genre']}
#     **분위기:** {row['Mood']}
#     **상황:** {row['Situation']}
#     **곡 길이:** {row['Length']}분
#     **에너지:** {row['Energy']}
#     **추천 점수:** {row['Recommendation Score']}
#     """)
#     st.progress(min(row["Recommendation Score"] / 120, 1.0))
# 
# st.markdown("---")
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     st.subheader("📊 추천 점수 비교")
#     fig = px.bar(top5, x="Title", y="Recommendation Score", color="Genre")
#     st.plotly_chart(fig, use_container_width=True)
# 
# with col2:
#     st.subheader("⚡ 에너지 vs 인기도")
#     fig2 = px.scatter(
#         recommended,
#         x="Energy",
#         y="Popularity",
#         size="Recommendation Score",
#         color="Mood",
#         hover_name="Title"
#     )
#     st.plotly_chart(fig2, use_container_width=True)
# 
# st.markdown("---")
# 
# st.subheader("📋 전체 노래 데이터")
# st.dataframe(recommended)
# 
# st.subheader("🧠 추천 메커니즘")
# st.write("""
# 이 앱은 단순히 장르만 보는 것이 아니라 여러 조건을 점수화합니다.
# 
# 1. 오늘 기분과 노래 분위기가 맞으면 점수 증가
# 2. 듣는 상황과 노래 상황이 맞으면 점수 증가
# 3. 선호 장르에 포함되면 점수 증가
# 4. 원하는 에너지와 가까울수록 점수 증가
# 5. 최대 곡 길이를 넘으면 감점
# 6. 인기도는 사용자가 정한 중요도만큼 반영
# """)

!streamlit run music_app.py \
    --server.headless true \
    --server.enableCORS false \
    --server.enableXsrfProtection false \
    --server.port 8501 > streamlit.log 2>&1 &

import time
time.sleep(5)

print("노래 추천 앱 실행 완료")

!./cloudflared tunnel --url http://localhost:8501